(TeX-add-style-hook
 "roughdraft"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "introduction"
    "prework"
    "reynolds"
    "prozess"
    "discussion"
    "article"
    "art10"
    "amssymb"
    "amsmath"
    "amsthm"
    "cite"
    "mathtools"
    "enumerate"
    "perpage")
   (LaTeX-add-labels
    "pw")
   (LaTeX-add-environments
    "theorem"
    "definition"
    "lemma"
    "proposition"
    "corollary"
    "remark"
    "cremark"
    "example"
    "dexample")
   (LaTeX-add-bibliographies))
 :latex)

